### ISSUE TITLE
Buen proyecto y buenas vistas 👍

### ISSUE THREAD

**Issue by AnderMendoza** [Mateoac12/portfolio#1]
Te quedo genial tu portafolio, muy minimalista y ordenado. El modo oscuro también te quedo genial, por cierto, tomo como guía el orden de tu curriculum 😁. Saludos.

**Comment by maadeval** [comment]
Ander muchas gracias!!! 😊 Me alegra mucho que te haya gustado! Y espero que tu curriculum quede genial!! Lo he hecho en Figma por si te sirve!! Es más denso que otras herramientas pero te da mucha libertad, muchos éxitos!! 🚀
